# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 196)
        font = QtGui.QFont()
        font.setItalic(False)
        Form.setFont(font)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 451, 128))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.timer = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(75)
        font.setItalic(False)
        self.timer.setFont(font)
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setObjectName("timer")
        self.verticalLayout.addWidget(self.timer)
        self.progressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_2.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.big_label = QtWidgets.QLabel(Form)
        self.big_label.setGeometry(QtCore.QRect(20, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(30)
        font.setItalic(False)
        self.big_label.setFont(font)
        self.big_label.setObjectName("big_label")
        self.edit_button = QtWidgets.QPushButton(Form)
        self.edit_button.setGeometry(QtCore.QRect(250, 150, 101, 32))
        self.edit_button.setObjectName("edit_button")
        self.developer_label = QtWidgets.QLabel(Form)
        self.developer_label.setGeometry(QtCore.QRect(20, 170, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        self.developer_label.setFont(font)
        self.developer_label.setObjectName("developer_label")
        self.reset_button = QtWidgets.QPushButton(Form)
        self.reset_button.setGeometry(QtCore.QRect(370, 150, 101, 32))
        self.reset_button.setObjectName("reset_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timer.setText(_translate("Form", "25:00"))
        self.start_button.setText(_translate("Form", "Start"))
        self.stop_button.setText(_translate("Form", "Stop"))
        self.big_label.setText(_translate("Form", "QT Pomo"))
        self.edit_button.setText(_translate("Form", "Edit Timer"))
        self.developer_label.setText(_translate("Form", " Developed by Max Santos"))
        self.reset_button.setText(_translate("Form", "Reset"))
